name: Build and publish Docker
on:
  push:
    
jobs:
  build_and_push:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
            docker build -t nanajanashia/k8s-demo-app:v1.0
